version: "1.0"
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: rewards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
  
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
  
  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - database
    ports:
      - '4000:4000'